/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.
*/
public class Solution {
    public char findTheDifference(String s, String t) {
        char res = (char)0;
        char[] sChars = s.toCharArray(),
               tChars = t.toCharArray();
        for(char c : sChars)
            res ^= c;
        for(char c : tChars)
            res ^= c;
        return res;
    }
}

public class Solution {
    public char findTheDifference(String s, String t) {
        char c = (char)0;
        for(int i = 0; i < s.length(); i++) c ^= s.charAt(i);
        for(int i = 0; i < t.length(); i++) c ^= t.charAt(i);
        return c;
    }
}

public class Solution {
    public char findTheDifference(String s, String t) {
        int [] m = new int[26];
        for(int i = 0; i < s.length(); i++)
            m[s.charAt(i) - 'a']++;

        for(int i = 0; i < t.length(); i++)
            m[t.charAt(i) - 'a']--;

        for(int i = 0; i < m.length; i++){
            if(m[i] == -1) return (char)('a' + i);
        }
        return 'A';
    }
}

public class Solution {
    public char findTheDifference(String s, String t) {
        int charCodeS = 0, charCodeT = 0;
        char[] sChars = s.toCharArray(),
               tChars = t.toCharArray();
        for(char c : sChars)
            charCodeS += (int)c;
        for(char c : tChars)
            charCodeT += (int)c;
        return (char)(charCodeT - charCodeS);
    }
}